---
name: PointDet
channels:
  - pytorch
  - nvidia/label/cuda-11.6.2
  - conda-forge
dependencies:
  - cudatoolkit=11.6
  - hydra-core
  - numba
  - pillow
  - pip
  - python=3.9
  - pytorch
  - tensorboard
  - tqdm
  # Linter
  - autoflake
  - black
  - cppcheck
  - isort
  - pylint
  - yamllint
  # Toolchain
  - clang-tools
  - cuda-toolkit
  - debugpy
  - gxx=11
  - ninja
  - pip:
      - git+https://github.com/facebookresearch/hydra#subdirectory=contrib/hydra_torchrun_launcher
